### ISSUE TITLE
Uncaught Exception on load of application

### ISSUE THREAD

**Issue by ageddesi** [GitbookIO/feedback#21]
I get this whenever I try to open the application. 

I am using a iMac with OS X El Captain 10.11.5

Uncaught Exception:
TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at Function.resolve (/Applications/GitBook Editor.app/Contents/Resources/app.asar/node_modules/parse-git-config/index.js:107:15)
    at Function.parseSync [as sync] (/Applications/GitBook Editor.app/Contents/Resources/app.asar/node_modules/parse-git-config/index.js:78:24)
    at o.defaultIdentity (/Applications/GitBook Editor.app/Contents/Resources/app.asar/main/index.js:1:973)
    at o.wrapper [as defaultIdentity] (/Applications/GitBook Editor.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:4436:19)
    at o.details (/Applications/GitBook Editor.app/Contents/Resources/app.asar/main/index.js:1:1418)
    at o.wrapper (/Applications/GitBook Editor.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:4436:19)
    at EventEmitter.t (/Applications/GitBook Editor.app/Contents/Resources/app.asar/main/index.js:1:7974)
    at emitOne (events.js:82:20)

**Comment by SamyPesse** [comment]
It should not be happening with latest release. Feel free to let me know otherwise.

**Comment by ageddesi** [comment]
I will check when back in the uk. Away on holiday until sunday :)
