### ISSUE TITLE
Gitbook shell gitbook build return error

### ISSUE THREAD

**Issue by mzkmzk** [GitbookIO/feedback#379]
~/GitBook/Library//Read   master ✔  gitbook --version
CLI version: 2.3.0
GitBook version: 2.6.4
 ~/GitBook/Library//Read   master ✔  gitbook build
Error loading version latest: Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/Users//.gitbook/versions/2.6.4/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

TypeError: Cannot read property 'commands' of null
 ~/GitBook/Library//Read   master ✔  node -v
v7.5.0

**Comment by japgolly** [comment]
Same here. Any luck fixing this?

**Comment by FGM** [comment]
Same here:
`node -v` -> v8.1.0
`npm -v` -> 5.0.3
```
npm ls --global graceful-fs
└─┬ gitbook-cli@2.3.0
  ├─┬ fs-extra@0.26.5
  │ ├── graceful-fs@4.1.11
  │ ├─┬ jsonfile@2.4.0
  │ │ └── graceful-fs@4.1.11  deduped
  │ └─┬ klaw@1.3.1
  │   └── graceful-fs@4.1.11  deduped
  ├─┬ npm@3.7.5
  │ ├─┬ cmd-shim@2.0.2
  │ │ └── graceful-fs@4.1.3  deduped
  │ ├─┬ fs-vacuum@1.2.7
  │ │ └── graceful-fs@4.1.3  deduped
  │ ├─┬ fs-write-stream-atomic@1.0.8
  │ │ └── graceful-fs@4.1.3  deduped
  │ ├─┬ fstream@1.0.8
  │ │ └── graceful-fs@4.1.3  deduped
  │ ├── graceful-fs@4.1.3
  │ ├─┬ node-gyp@3.3.0
  │ │ └── graceful-fs@4.1.3  deduped
  │ ├─┬ npm-registry-client@7.0.9
  │ │ └── graceful-fs@4.1.3  deduped
  │ ├─┬ read-cmd-shim@1.0.1
  │ │ └── graceful-fs@4.1.3  deduped
  │ ├─┬ read-installed@4.0.3
  │ │ └── graceful-fs@4.1.3  deduped
  │ ├─┬ read-package-json@2.0.3
  │ │ └── graceful-fs@4.1.3  deduped
  │ ├─┬ readdir-scoped-modules@1.0.2
  │ │ └── graceful-fs@4.1.3  deduped
  │ ├─┬ sha@2.0.1
  │ │ └── graceful-fs@4.1.3  deduped
  │ └─┬ write-file-atomic@1.1.4
  │   └── graceful-fs@4.1.3  deduped
  └─┬ npmi@1.0.1
    └─┬ npm@2.15.12
      ├─┬ cmd-shim@2.0.2
      │ └── graceful-fs@4.1.6  deduped
      ├─┬ fs-vacuum@1.2.9
      │ └── graceful-fs@4.1.6  deduped
      ├─┬ fs-write-stream-atomic@1.0.8
      │ └── graceful-fs@4.1.6  deduped
      ├─┬ fstream@1.0.10
      │ └── graceful-fs@4.1.6  deduped
      ├── graceful-fs@4.1.6
      ├─┬ node-gyp@3.6.0
      │ └── graceful-fs@4.1.6  deduped
      ├─┬ npm-registry-client@7.2.1
      │ └── graceful-fs@4.1.6  deduped
      ├─┬ read-installed@4.0.3
      │ ├── graceful-fs@4.1.6  deduped
      │ └─┬ readdir-scoped-modules@1.0.2
      │   └── graceful-fs@4.1.6  deduped
      ├─┬ read-package-json@2.0.4
      │ └── graceful-fs@4.1.6  deduped
      ├─┬ sha@2.0.1
      │ └── graceful-fs@4.1.6  deduped
      └─┬ write-file-atomic@1.1.4
        └── graceful-fs@4.1.6  deduped
```

This is on macOS Sierra, after completely wiping node and npm, the cache in ~/npm and everything node-related in /usr/local and doing a fresh `brew install node` then `npm i -g docbook-cli`. Same after another clean and `yarn global add gitbook-cli`.

**Comment by AntiMoron** [comment]
Same

**Comment by smdahmed** [comment]
Same
